# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cg_fpga_0_0/design_1_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cg_fpga_0_0 || ORIG_REF_NAME==design_1_cg_fpga_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adpt_in_0_1/design_1_adpt_in_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adpt_in_0_1 || ORIG_REF_NAME==design_1_adpt_in_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adpt_in_1_1/design_1_adpt_in_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adpt_in_1_1 || ORIG_REF_NAME==design_1_adpt_in_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_1/design_1_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_1 || ORIG_REF_NAME==design_1_xlconstant_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_0_2/design_1_or_gate_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_0_2 || ORIG_REF_NAME==design_1_or_gate_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_1_1/design_1_or_gate_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_1_1 || ORIG_REF_NAME==design_1_or_gate_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_2_1/design_1_or_gate_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_2_1 || ORIG_REF_NAME==design_1_or_gate_2_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_3_1/design_1_or_gate_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_3_1 || ORIG_REF_NAME==design_1_or_gate_3_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_4_2/design_1_or_gate_4_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_4_2 || ORIG_REF_NAME==design_1_or_gate_4_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_0_1/design_1_and_gate_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_0_1 || ORIG_REF_NAME==design_1_and_gate_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_0_2/design_1_and_gate_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_0_2 || ORIG_REF_NAME==design_1_and_gate_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_0_3/design_1_and_gate_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_0_3 || ORIG_REF_NAME==design_1_and_gate_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_0_4/design_1_and_gate_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_0_4 || ORIG_REF_NAME==design_1_and_gate_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_0_5/design_1_and_gate_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_0_5 || ORIG_REF_NAME==design_1_and_gate_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_0_6/design_1_and_gate_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_0_6 || ORIG_REF_NAME==design_1_and_gate_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_0_1/design_1_xor_gate_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_0_1 || ORIG_REF_NAME==design_1_xor_gate_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_1_1/design_1_xor_gate_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_1_1 || ORIG_REF_NAME==design_1_xor_gate_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_2_1/design_1_xor_gate_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_2_1 || ORIG_REF_NAME==design_1_xor_gate_2_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_2_2/design_1_xor_gate_2_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_2_2 || ORIG_REF_NAME==design_1_xor_gate_2_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_2_3/design_1_xor_gate_2_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_2_3 || ORIG_REF_NAME==design_1_xor_gate_2_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_2_4/design_1_xor_gate_2_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_2_4 || ORIG_REF_NAME==design_1_xor_gate_2_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_2_5/design_1_xor_gate_2_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_2_5 || ORIG_REF_NAME==design_1_xor_gate_2_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_7_0/design_1_xor_gate_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_7_0 || ORIG_REF_NAME==design_1_xor_gate_7_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_5_0/design_1_or_gate_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_5_0 || ORIG_REF_NAME==design_1_or_gate_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_7_0/design_1_and_gate_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_7_0 || ORIG_REF_NAME==design_1_and_gate_7_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_0_0/design_1_and_gate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_0_0 || ORIG_REF_NAME==design_1_and_gate_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_5/design_1_xlconstant_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_5 || ORIG_REF_NAME==design_1_xlconstant_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_0_6/design_1_or_gate_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_0_6 || ORIG_REF_NAME==design_1_or_gate_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_1_5/design_1_or_gate_1_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_1_5 || ORIG_REF_NAME==design_1_or_gate_1_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_2_5/design_1_or_gate_2_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_2_5 || ORIG_REF_NAME==design_1_or_gate_2_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_3_5/design_1_or_gate_3_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_3_5 || ORIG_REF_NAME==design_1_or_gate_3_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_4_6/design_1_or_gate_4_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_4_6 || ORIG_REF_NAME==design_1_or_gate_4_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_1_5/design_1_and_gate_1_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_1_5 || ORIG_REF_NAME==design_1_and_gate_1_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_2_5/design_1_and_gate_2_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_2_5 || ORIG_REF_NAME==design_1_and_gate_2_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_3_5/design_1_and_gate_3_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_3_5 || ORIG_REF_NAME==design_1_and_gate_3_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_4_5/design_1_and_gate_4_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_4_5 || ORIG_REF_NAME==design_1_and_gate_4_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_5_5/design_1_and_gate_5_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_5_5 || ORIG_REF_NAME==design_1_and_gate_5_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_6_5/design_1_and_gate_6_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_6_5 || ORIG_REF_NAME==design_1_and_gate_6_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_0_5/design_1_xor_gate_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_0_5 || ORIG_REF_NAME==design_1_xor_gate_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_1_5/design_1_xor_gate_1_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_1_5 || ORIG_REF_NAME==design_1_xor_gate_1_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_2_9/design_1_xor_gate_2_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_2_9 || ORIG_REF_NAME==design_1_xor_gate_2_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_3_4/design_1_xor_gate_3_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_3_4 || ORIG_REF_NAME==design_1_xor_gate_3_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_4_4/design_1_xor_gate_4_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_4_4 || ORIG_REF_NAME==design_1_xor_gate_4_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_5_4/design_1_xor_gate_5_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_5_4 || ORIG_REF_NAME==design_1_xor_gate_5_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_6_4/design_1_xor_gate_6_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_6_4 || ORIG_REF_NAME==design_1_xor_gate_6_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_7_3/design_1_xor_gate_7_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_7_3 || ORIG_REF_NAME==design_1_xor_gate_7_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_5_3/design_1_or_gate_5_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_5_3 || ORIG_REF_NAME==design_1_or_gate_5_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_7_4/design_1_and_gate_7_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_7_4 || ORIG_REF_NAME==design_1_and_gate_7_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_0_11/design_1_and_gate_0_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_0_11 || ORIG_REF_NAME==design_1_and_gate_0_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_6/design_1_xlconstant_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_6 || ORIG_REF_NAME==design_1_xlconstant_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_8_0/design_1_and_gate_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_8_0 || ORIG_REF_NAME==design_1_and_gate_8_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_9_0/design_1_and_gate_9_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_9_0 || ORIG_REF_NAME==design_1_and_gate_9_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_10_0/design_1_and_gate_10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_10_0 || ORIG_REF_NAME==design_1_and_gate_10_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_11_0/design_1_and_gate_11_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_11_0 || ORIG_REF_NAME==design_1_and_gate_11_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_12_0/design_1_and_gate_12_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_12_0 || ORIG_REF_NAME==design_1_and_gate_12_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_13_0/design_1_and_gate_13_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_13_0 || ORIG_REF_NAME==design_1_and_gate_13_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_14_0/design_1_and_gate_14_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_14_0 || ORIG_REF_NAME==design_1_and_gate_14_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_15_0/design_1_and_gate_15_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_15_0 || ORIG_REF_NAME==design_1_and_gate_15_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_8_0/design_1_full_add_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_8_0 || ORIG_REF_NAME==design_1_full_add_8_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_9_0/design_1_full_add_9_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_9_0 || ORIG_REF_NAME==design_1_full_add_9_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_10_0/design_1_full_add_10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_10_0 || ORIG_REF_NAME==design_1_full_add_10_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_11_0/design_1_full_add_11_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_11_0 || ORIG_REF_NAME==design_1_full_add_11_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_12_0/design_1_full_add_12_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_12_0 || ORIG_REF_NAME==design_1_full_add_12_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_13_0/design_1_full_add_13_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_13_0 || ORIG_REF_NAME==design_1_full_add_13_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_14_0/design_1_full_add_14_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_14_0 || ORIG_REF_NAME==design_1_full_add_14_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_15_0/design_1_full_add_15_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_15_0 || ORIG_REF_NAME==design_1_full_add_15_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_0_10/design_1_and_gate_0_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_0_10 || ORIG_REF_NAME==design_1_and_gate_0_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_1_4/design_1_and_gate_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_1_4 || ORIG_REF_NAME==design_1_and_gate_1_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_2_4/design_1_and_gate_2_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_2_4 || ORIG_REF_NAME==design_1_and_gate_2_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_3_4/design_1_and_gate_3_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_3_4 || ORIG_REF_NAME==design_1_and_gate_3_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_4_4/design_1_and_gate_4_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_4_4 || ORIG_REF_NAME==design_1_and_gate_4_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_5_4/design_1_and_gate_5_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_5_4 || ORIG_REF_NAME==design_1_and_gate_5_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_6_4/design_1_and_gate_6_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_6_4 || ORIG_REF_NAME==design_1_and_gate_6_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_7_3/design_1_and_gate_7_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_7_3 || ORIG_REF_NAME==design_1_and_gate_7_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_0_0/design_1_full_add_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_0_0 || ORIG_REF_NAME==design_1_full_add_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_1_0/design_1_full_add_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_1_0 || ORIG_REF_NAME==design_1_full_add_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_2_0/design_1_full_add_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_2_0 || ORIG_REF_NAME==design_1_full_add_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_3_0/design_1_full_add_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_3_0 || ORIG_REF_NAME==design_1_full_add_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_4_0/design_1_full_add_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_4_0 || ORIG_REF_NAME==design_1_full_add_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_5_0/design_1_full_add_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_5_0 || ORIG_REF_NAME==design_1_full_add_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_6_0/design_1_full_add_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_6_0 || ORIG_REF_NAME==design_1_full_add_6_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_7_0/design_1_full_add_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_7_0 || ORIG_REF_NAME==design_1_full_add_7_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_8_2/design_1_and_gate_8_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_8_2 || ORIG_REF_NAME==design_1_and_gate_8_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_9_2/design_1_and_gate_9_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_9_2 || ORIG_REF_NAME==design_1_and_gate_9_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_10_2/design_1_and_gate_10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_10_2 || ORIG_REF_NAME==design_1_and_gate_10_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_11_2/design_1_and_gate_11_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_11_2 || ORIG_REF_NAME==design_1_and_gate_11_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_12_2/design_1_and_gate_12_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_12_2 || ORIG_REF_NAME==design_1_and_gate_12_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_13_2/design_1_and_gate_13_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_13_2 || ORIG_REF_NAME==design_1_and_gate_13_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_14_2/design_1_and_gate_14_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_14_2 || ORIG_REF_NAME==design_1_and_gate_14_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_15_2/design_1_and_gate_15_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_15_2 || ORIG_REF_NAME==design_1_and_gate_15_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_8_2/design_1_full_add_8_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_8_2 || ORIG_REF_NAME==design_1_full_add_8_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_9_2/design_1_full_add_9_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_9_2 || ORIG_REF_NAME==design_1_full_add_9_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_10_2/design_1_full_add_10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_10_2 || ORIG_REF_NAME==design_1_full_add_10_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_11_2/design_1_full_add_11_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_11_2 || ORIG_REF_NAME==design_1_full_add_11_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_12_2/design_1_full_add_12_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_12_2 || ORIG_REF_NAME==design_1_full_add_12_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_13_2/design_1_full_add_13_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_13_2 || ORIG_REF_NAME==design_1_full_add_13_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_14_2/design_1_full_add_14_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_14_2 || ORIG_REF_NAME==design_1_full_add_14_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_15_2/design_1_full_add_15_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_15_2 || ORIG_REF_NAME==design_1_full_add_15_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_8_3/design_1_and_gate_8_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_8_3 || ORIG_REF_NAME==design_1_and_gate_8_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_9_3/design_1_and_gate_9_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_9_3 || ORIG_REF_NAME==design_1_and_gate_9_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_10_3/design_1_and_gate_10_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_10_3 || ORIG_REF_NAME==design_1_and_gate_10_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_11_3/design_1_and_gate_11_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_11_3 || ORIG_REF_NAME==design_1_and_gate_11_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_12_3/design_1_and_gate_12_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_12_3 || ORIG_REF_NAME==design_1_and_gate_12_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_13_3/design_1_and_gate_13_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_13_3 || ORIG_REF_NAME==design_1_and_gate_13_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_14_3/design_1_and_gate_14_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_14_3 || ORIG_REF_NAME==design_1_and_gate_14_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_15_3/design_1_and_gate_15_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_15_3 || ORIG_REF_NAME==design_1_and_gate_15_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_8_3/design_1_full_add_8_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_8_3 || ORIG_REF_NAME==design_1_full_add_8_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_9_3/design_1_full_add_9_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_9_3 || ORIG_REF_NAME==design_1_full_add_9_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_10_3/design_1_full_add_10_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_10_3 || ORIG_REF_NAME==design_1_full_add_10_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_11_3/design_1_full_add_11_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_11_3 || ORIG_REF_NAME==design_1_full_add_11_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_12_3/design_1_full_add_12_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_12_3 || ORIG_REF_NAME==design_1_full_add_12_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_13_3/design_1_full_add_13_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_13_3 || ORIG_REF_NAME==design_1_full_add_13_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_14_3/design_1_full_add_14_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_14_3 || ORIG_REF_NAME==design_1_full_add_14_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_15_3/design_1_full_add_15_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_15_3 || ORIG_REF_NAME==design_1_full_add_15_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_8_4/design_1_and_gate_8_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_8_4 || ORIG_REF_NAME==design_1_and_gate_8_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_9_4/design_1_and_gate_9_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_9_4 || ORIG_REF_NAME==design_1_and_gate_9_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_10_4/design_1_and_gate_10_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_10_4 || ORIG_REF_NAME==design_1_and_gate_10_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_11_4/design_1_and_gate_11_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_11_4 || ORIG_REF_NAME==design_1_and_gate_11_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_12_4/design_1_and_gate_12_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_12_4 || ORIG_REF_NAME==design_1_and_gate_12_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_13_4/design_1_and_gate_13_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_13_4 || ORIG_REF_NAME==design_1_and_gate_13_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_14_4/design_1_and_gate_14_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_14_4 || ORIG_REF_NAME==design_1_and_gate_14_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_15_4/design_1_and_gate_15_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_15_4 || ORIG_REF_NAME==design_1_and_gate_15_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_8_4/design_1_full_add_8_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_8_4 || ORIG_REF_NAME==design_1_full_add_8_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_9_4/design_1_full_add_9_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_9_4 || ORIG_REF_NAME==design_1_full_add_9_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_10_4/design_1_full_add_10_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_10_4 || ORIG_REF_NAME==design_1_full_add_10_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_11_4/design_1_full_add_11_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_11_4 || ORIG_REF_NAME==design_1_full_add_11_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_12_4/design_1_full_add_12_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_12_4 || ORIG_REF_NAME==design_1_full_add_12_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_13_4/design_1_full_add_13_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_13_4 || ORIG_REF_NAME==design_1_full_add_13_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_14_4/design_1_full_add_14_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_14_4 || ORIG_REF_NAME==design_1_full_add_14_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_15_4/design_1_full_add_15_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_15_4 || ORIG_REF_NAME==design_1_full_add_15_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_8_5/design_1_and_gate_8_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_8_5 || ORIG_REF_NAME==design_1_and_gate_8_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_9_5/design_1_and_gate_9_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_9_5 || ORIG_REF_NAME==design_1_and_gate_9_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_10_5/design_1_and_gate_10_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_10_5 || ORIG_REF_NAME==design_1_and_gate_10_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_11_5/design_1_and_gate_11_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_11_5 || ORIG_REF_NAME==design_1_and_gate_11_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_12_5/design_1_and_gate_12_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_12_5 || ORIG_REF_NAME==design_1_and_gate_12_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_13_5/design_1_and_gate_13_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_13_5 || ORIG_REF_NAME==design_1_and_gate_13_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_14_5/design_1_and_gate_14_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_14_5 || ORIG_REF_NAME==design_1_and_gate_14_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_15_5/design_1_and_gate_15_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_15_5 || ORIG_REF_NAME==design_1_and_gate_15_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_8_5/design_1_full_add_8_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_8_5 || ORIG_REF_NAME==design_1_full_add_8_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_9_5/design_1_full_add_9_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_9_5 || ORIG_REF_NAME==design_1_full_add_9_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_10_5/design_1_full_add_10_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_10_5 || ORIG_REF_NAME==design_1_full_add_10_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_11_5/design_1_full_add_11_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_11_5 || ORIG_REF_NAME==design_1_full_add_11_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_12_5/design_1_full_add_12_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_12_5 || ORIG_REF_NAME==design_1_full_add_12_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_13_5/design_1_full_add_13_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_13_5 || ORIG_REF_NAME==design_1_full_add_13_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_14_5/design_1_full_add_14_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_14_5 || ORIG_REF_NAME==design_1_full_add_14_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_15_5/design_1_full_add_15_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_15_5 || ORIG_REF_NAME==design_1_full_add_15_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_8_6/design_1_and_gate_8_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_8_6 || ORIG_REF_NAME==design_1_and_gate_8_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_9_6/design_1_and_gate_9_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_9_6 || ORIG_REF_NAME==design_1_and_gate_9_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_10_6/design_1_and_gate_10_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_10_6 || ORIG_REF_NAME==design_1_and_gate_10_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_11_6/design_1_and_gate_11_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_11_6 || ORIG_REF_NAME==design_1_and_gate_11_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_12_6/design_1_and_gate_12_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_12_6 || ORIG_REF_NAME==design_1_and_gate_12_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_13_6/design_1_and_gate_13_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_13_6 || ORIG_REF_NAME==design_1_and_gate_13_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_14_6/design_1_and_gate_14_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_14_6 || ORIG_REF_NAME==design_1_and_gate_14_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_15_6/design_1_and_gate_15_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_15_6 || ORIG_REF_NAME==design_1_and_gate_15_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_8_6/design_1_full_add_8_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_8_6 || ORIG_REF_NAME==design_1_full_add_8_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_9_6/design_1_full_add_9_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_9_6 || ORIG_REF_NAME==design_1_full_add_9_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_10_6/design_1_full_add_10_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_10_6 || ORIG_REF_NAME==design_1_full_add_10_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_11_6/design_1_full_add_11_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_11_6 || ORIG_REF_NAME==design_1_full_add_11_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_12_6/design_1_full_add_12_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_12_6 || ORIG_REF_NAME==design_1_full_add_12_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_13_6/design_1_full_add_13_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_13_6 || ORIG_REF_NAME==design_1_full_add_13_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_14_6/design_1_full_add_14_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_14_6 || ORIG_REF_NAME==design_1_full_add_14_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_15_6/design_1_full_add_15_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_15_6 || ORIG_REF_NAME==design_1_full_add_15_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_8_7/design_1_and_gate_8_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_8_7 || ORIG_REF_NAME==design_1_and_gate_8_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_9_7/design_1_and_gate_9_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_9_7 || ORIG_REF_NAME==design_1_and_gate_9_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_10_7/design_1_and_gate_10_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_10_7 || ORIG_REF_NAME==design_1_and_gate_10_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_11_7/design_1_and_gate_11_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_11_7 || ORIG_REF_NAME==design_1_and_gate_11_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_12_7/design_1_and_gate_12_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_12_7 || ORIG_REF_NAME==design_1_and_gate_12_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_13_7/design_1_and_gate_13_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_13_7 || ORIG_REF_NAME==design_1_and_gate_13_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_14_7/design_1_and_gate_14_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_14_7 || ORIG_REF_NAME==design_1_and_gate_14_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_15_7/design_1_and_gate_15_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_15_7 || ORIG_REF_NAME==design_1_and_gate_15_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_8_7/design_1_full_add_8_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_8_7 || ORIG_REF_NAME==design_1_full_add_8_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_9_7/design_1_full_add_9_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_9_7 || ORIG_REF_NAME==design_1_full_add_9_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_10_7/design_1_full_add_10_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_10_7 || ORIG_REF_NAME==design_1_full_add_10_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_11_7/design_1_full_add_11_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_11_7 || ORIG_REF_NAME==design_1_full_add_11_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_12_7/design_1_full_add_12_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_12_7 || ORIG_REF_NAME==design_1_full_add_12_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_13_7/design_1_full_add_13_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_13_7 || ORIG_REF_NAME==design_1_full_add_13_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_14_7/design_1_full_add_14_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_14_7 || ORIG_REF_NAME==design_1_full_add_14_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_full_add_15_7/design_1_full_add_15_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_full_add_15_7 || ORIG_REF_NAME==design_1_full_add_15_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_0_8/design_1_xor_gate_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_0_8 || ORIG_REF_NAME==design_1_xor_gate_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adpt_out_0_1/design_1_adpt_out_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adpt_out_0_1 || ORIG_REF_NAME==design_1_adpt_out_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_7/design_1_xlconstant_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_7 || ORIG_REF_NAME==design_1_xlconstant_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_0_7/design_1_or_gate_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_0_7 || ORIG_REF_NAME==design_1_or_gate_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_1_6/design_1_or_gate_1_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_1_6 || ORIG_REF_NAME==design_1_or_gate_1_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_2_6/design_1_or_gate_2_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_2_6 || ORIG_REF_NAME==design_1_or_gate_2_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_3_6/design_1_or_gate_3_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_3_6 || ORIG_REF_NAME==design_1_or_gate_3_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_4_7/design_1_or_gate_4_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_4_7 || ORIG_REF_NAME==design_1_or_gate_4_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_1_6/design_1_and_gate_1_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_1_6 || ORIG_REF_NAME==design_1_and_gate_1_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_2_6/design_1_and_gate_2_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_2_6 || ORIG_REF_NAME==design_1_and_gate_2_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_3_6/design_1_and_gate_3_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_3_6 || ORIG_REF_NAME==design_1_and_gate_3_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_4_6/design_1_and_gate_4_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_4_6 || ORIG_REF_NAME==design_1_and_gate_4_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_5_6/design_1_and_gate_5_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_5_6 || ORIG_REF_NAME==design_1_and_gate_5_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_6_6/design_1_and_gate_6_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_6_6 || ORIG_REF_NAME==design_1_and_gate_6_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_0_9/design_1_xor_gate_0_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_0_9 || ORIG_REF_NAME==design_1_xor_gate_0_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_1_6/design_1_xor_gate_1_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_1_6 || ORIG_REF_NAME==design_1_xor_gate_1_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_2_10/design_1_xor_gate_2_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_2_10 || ORIG_REF_NAME==design_1_xor_gate_2_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_3_5/design_1_xor_gate_3_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_3_5 || ORIG_REF_NAME==design_1_xor_gate_3_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_4_5/design_1_xor_gate_4_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_4_5 || ORIG_REF_NAME==design_1_xor_gate_4_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_5_5/design_1_xor_gate_5_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_5_5 || ORIG_REF_NAME==design_1_xor_gate_5_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_6_5/design_1_xor_gate_6_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_6_5 || ORIG_REF_NAME==design_1_xor_gate_6_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_7_4/design_1_xor_gate_7_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_7_4 || ORIG_REF_NAME==design_1_xor_gate_7_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_5_4/design_1_or_gate_5_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_5_4 || ORIG_REF_NAME==design_1_or_gate_5_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_7_5/design_1_and_gate_7_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_7_5 || ORIG_REF_NAME==design_1_and_gate_7_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_0_12/design_1_and_gate_0_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_0_12 || ORIG_REF_NAME==design_1_and_gate_0_12} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_0_8/design_1_or_gate_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_0_8 || ORIG_REF_NAME==design_1_or_gate_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_1_7/design_1_or_gate_1_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_1_7 || ORIG_REF_NAME==design_1_or_gate_1_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_2_7/design_1_or_gate_2_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_2_7 || ORIG_REF_NAME==design_1_or_gate_2_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_3_7/design_1_or_gate_3_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_3_7 || ORIG_REF_NAME==design_1_or_gate_3_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_4_8/design_1_or_gate_4_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_4_8 || ORIG_REF_NAME==design_1_or_gate_4_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_1_7/design_1_and_gate_1_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_1_7 || ORIG_REF_NAME==design_1_and_gate_1_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_2_7/design_1_and_gate_2_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_2_7 || ORIG_REF_NAME==design_1_and_gate_2_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_3_7/design_1_and_gate_3_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_3_7 || ORIG_REF_NAME==design_1_and_gate_3_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_4_7/design_1_and_gate_4_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_4_7 || ORIG_REF_NAME==design_1_and_gate_4_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_5_7/design_1_and_gate_5_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_5_7 || ORIG_REF_NAME==design_1_and_gate_5_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_6_7/design_1_and_gate_6_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_6_7 || ORIG_REF_NAME==design_1_and_gate_6_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_0_10/design_1_xor_gate_0_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_0_10 || ORIG_REF_NAME==design_1_xor_gate_0_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_1_7/design_1_xor_gate_1_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_1_7 || ORIG_REF_NAME==design_1_xor_gate_1_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_2_11/design_1_xor_gate_2_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_2_11 || ORIG_REF_NAME==design_1_xor_gate_2_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_3_6/design_1_xor_gate_3_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_3_6 || ORIG_REF_NAME==design_1_xor_gate_3_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_4_6/design_1_xor_gate_4_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_4_6 || ORIG_REF_NAME==design_1_xor_gate_4_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_5_6/design_1_xor_gate_5_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_5_6 || ORIG_REF_NAME==design_1_xor_gate_5_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_6_6/design_1_xor_gate_6_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_6_6 || ORIG_REF_NAME==design_1_xor_gate_6_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_gate_7_5/design_1_xor_gate_7_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor_gate_7_5 || ORIG_REF_NAME==design_1_xor_gate_7_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_5_5/design_1_or_gate_5_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_5_5 || ORIG_REF_NAME==design_1_or_gate_5_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_7_6/design_1_and_gate_7_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_7_6 || ORIG_REF_NAME==design_1_and_gate_7_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_0_13/design_1_and_gate_0_13.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and_gate_0_13 || ORIG_REF_NAME==design_1_and_gate_0_13} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_6_0/design_1_or_gate_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_6_0 || ORIG_REF_NAME==design_1_or_gate_6_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_gate_7_0/design_1_or_gate_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or_gate_7_0 || ORIG_REF_NAME==design_1_or_gate_7_0} -quiet] -quiet

# XDC: d:/coding/computer_organization/exp2nd/multi/multi/multi.gen/sources_1/bd/design_1/design_1_ooc.xdc
